language: python

dist: xenial
sudo: false

matrix:
  include:
    - python: 3.8
      env: TOX_ENV='flake8'
    - python: 3.8
      env: TOX_ENV='isort'
    - python: 3.8
      env: CMS='cms311'
    - python: 3.9
      env: CMS='cms311'
    - python: 3.10
      env: CMS='cms311'

install:
  - pip install coverage tox
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then export PY_VER=py38; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.9' ]]; then export PY_VER=py39; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.10' ]]; then export PY_VER=py310; fi"
  - "if [[ ${DJANGO}z != 'z' ]]; then export TOX_ENV=$PY_VER-$DJANGO-$CMS; fi"

script:
  - tox -e $TOX_ENV

after_success:
  - bash <(curl -s https://codecov.io/bash)
